// src/services/webhook.service.js
// Handles inbound SMS from Twilio — the offline SOS fallback path, plus a
// plain-text "SAFE" check-in a tourist can send by hand from any phone with
// zero data connectivity (the structured AARAKSHA_SOS pattern below is
// generated by the app itself via an sms: URI — not something a person
// types from memory, which is fine for the rare SOS case but wrong for a
// routine check-in someone should be able to send from a borrowed phone or
// a basic handset with no app installed at all).
'use strict'

const { InboundRepository } = require('../repositories/inbound.repository')
const { TouristRepository } = require('../repositories/tourist.repository')
const { SOSRepository }     = require('../repositories/sos.repository')
const { LocationRepository }= require('../repositories/location.repository')
const { CheckinRepository } = require('../repositories/checkin.repository')
const { DMSRepository }     = require('../repositories/dms.repository')
const { withTransaction }   = require('../database/transaction')
const { emitSOSReceived, emitGuardianSOSAlert, emitCheckinUpdate } = require('../socket/emitters')
const { notifyOnSOS }       = require('./notification/notification.service')
const { normalizePhone }    = require('../utils/crypto')
const { SOS_CATEGORIES, SOS_TRIGGER_TYPES, CHECKIN_TYPES, DMS_STATUSES } = require('../constants/enums')
const logger = require('../utils/logger')

// Regex pattern for structured offline SOS SMS
const SOS_PATTERN = /AARAKSHA_SOS\|ID:([a-f0-9-]{36})\|LAT:(-?\d+\.?\d*)\|LNG:(-?\d+\.?\d*)\|CAT:([A-Z]+)\|BATT:(\d+)\|TIME:(\d+)/

// Deliberately forgiving — a tourist typing this by hand under stress
// shouldn't need exact casing or punctuation. Matches "SAFE", "safe.",
// "I'm safe", "OK", "CHECKIN" as the first meaningful word.
const CHECKIN_PATTERN = /^\s*(?:i'?m\s+)?(SAFE|OK|OKAY|CHECKIN|CHECK-IN)\b/i

// Cheap, synchronous — lets the controller pick the right immediate TwiML
// reply before the actual (async) processing below has even started. The
// controller can't wait for processInboundSMS to resolve before replying
// (Twilio needs a response within 5s and processInboundSMS is deliberately
// fire-and-forget), so without this every inbound text — including a plain
// "SAFE" check-in — got back the SOS-alarm reply text unconditionally.
function classifyInboundSMS(body) {
  if (CHECKIN_PATTERN.test(body || '')) return 'CHECKIN'
  if (SOS_PATTERN.test(body || '')) return 'SOS'
  return 'UNKNOWN'
}

async function processInboundSMS(fromPhone, body) {
  const inboundRepo = new InboundRepository()
  const record      = await inboundRepo.create(fromPhone, body)

  if (CHECKIN_PATTERN.test(body || '')) {
    return processCheckinSMS(fromPhone, record, inboundRepo)
  }

  const match = body?.match(SOS_PATTERN)
  if (!match) {
    await inboundRepo.markFailed(record.id, `Pattern not matched. Body: ${body?.slice(0, 100)}`)
    logger.warn({ from: fromPhone }, 'Inbound SMS did not match SOS pattern — ignored')
    return
  }

  const [, touristId, latStr, lngStr, category, battStr, timeStr] = match
  const lat     = parseFloat(latStr)
  const lng     = parseFloat(lngStr)
  const battery = parseInt(battStr, 10)
  const timestamp = parseInt(timeStr, 10) * 1000

  // Validate coordinates
  if (isNaN(lat) || lat < -90 || lat > 90 || isNaN(lng) || lng < -180 || lng > 180) {
    await inboundRepo.markFailed(record.id, `Invalid coordinates: lat=${latStr} lng=${lngStr}`)
    return
  }

  // Validate category
  const validCategory = Object.values(SOS_CATEGORIES).includes(category) ? category : SOS_CATEGORIES.OTHER

  // Check location staleness (> 30 minutes old)
  const isStale = Date.now() - timestamp > 30 * 60 * 1000

  const touristRepo = new TouristRepository()
  const tourist = await touristRepo.findById(touristId)

  if (!tourist || !tourist.is_active) {
    await inboundRepo.markFailed(record.id, `Tourist not found or inactive: ${touristId}`)
    logger.warn({ touristId, from: fromPhone }, 'Inbound SOS — tourist not found')
    return
  }

  // Create SOS event in transaction
  const { sosEvent, isDuplicate } = await withTransaction(async (client) => {
    const sosRepo_t      = new SOSRepository(client)
    const locationRepo_t = new LocationRepository(client)

    // Same dedup guard as sos.service.js#createSOS and dms.service.js's
    // cron trigger: a tourist mid-incident (already fired from the app or
    // DMS) whose SMS then arrives — network retries, a resend after not
    // seeing a reply, or the app's own POST eventually going through too —
    // must not spawn a second ACTIVE row. This path was the one gap: it
    // called sosRepo_t.create() directly instead of going through
    // sos.service.js#createSOS, so it never got this check at all.
    const existingActive = await sosRepo_t.findLatestActiveByTouristId(tourist.id)
    if (existingActive) {
      const sosEvent = await sosRepo_t.findById(existingActive.id)
      return { sosEvent, isDuplicate: true }
    }

    const sosEvent = await sosRepo_t.create({
      touristId:       tourist.id,
      tripId:          null,
      latitude:        lat,
      longitude:       lng,
      isStaleLocation: isStale,
      category:        validCategory,
      triggerType:     SOS_TRIGGER_TYPES.SMS_INBOUND,
      batteryPct:      battery,
      message:         `Offline SOS via SMS. Timestamp: ${new Date(timestamp).toISOString()}${isStale ? ' [STALE LOCATION]' : ''}`,
    })

    // Update location from the SMS (may be stale but it's what we have)
    await locationRepo_t.upsert(tourist.id, { latitude: lat, longitude: lng, batteryPct: battery })

    return { sosEvent, isDuplicate: false }
  })

  // Update inbound record — even a suppressed duplicate is linked to the
  // (existing) SOS it maps to, so the audit trail shows this SMS arrived.
  await inboundRepo.markParsed(record.id, tourist.id, sosEvent.id)

  if (isDuplicate) {
    logger.info({ sosId: sosEvent.id, touristId: tourist.id, from: fromPhone }, 'Duplicate SMS SOS suppressed — incident already active')
    return
  }

  // Side effects outside transaction. emitGuardianSOSAlert was missing
  // entirely on this path — the one trigger path where the guardian NOT
  // being notified matters most, since the tourist has no signal to call
  // them directly either. Matches what sos.service.js#createSOS and
  // dms.service.js#processDMSTriggers already do for their own triggers.
  emitSOSReceived(sosEvent, tourist)
  emitGuardianSOSAlert(tourist.guardian_token, sosEvent, tourist)
  notifyOnSOS(tourist, sosEvent).catch(err =>
    logger.error({ err: err.message, sosId: sosEvent.id }, 'Inbound SOS notification failed')
  )

  logger.warn({
    sosId:     sosEvent.id,
    touristId: tourist.id,
    category:  validCategory,
    isStale,
    from:      fromPhone,
  }, 'Offline SOS processed from inbound SMS')
}

// "Text SAFE to check in" — identifies the tourist by their registered
// phone number (unlike the structured SOS path, which embeds the tourist's
// ID in the message itself, since an SOS might be sent from a borrowed
// phone). No GPS/battery required — those columns are nullable — so this
// works from literally any phone that can send a text, matching the
// low-connectivity NE India use case this app is built around.
async function processCheckinSMS(fromPhone, record, inboundRepo) {
  const touristRepo = new TouristRepository()
  const tourist = await touristRepo.findByPhone(normalizePhone(fromPhone))

  if (!tourist || !tourist.is_active) {
    await inboundRepo.markFailed(record.id, `SMS check-in — no registered tourist for phone ${fromPhone}`)
    logger.warn({ from: fromPhone }, 'SMS check-in — no matching tourist')
    return
  }

  const { checkin, dmsReset } = await withTransaction(async (client) => {
    const checkinRepo = new CheckinRepository(client)
    const dmsRepo      = new DMSRepository(client)

    const activeDms = await dmsRepo.findActiveByTouristId(tourist.id)
    const dmsIsActive = activeDms?.status === DMS_STATUSES.ACTIVE
    const dmsId = dmsIsActive ? activeDms.id : null

    const checkin = await checkinRepo.create({
      touristId: tourist.id,
      dmsId,
      latitude: null,
      longitude: null,
      message: 'Checked in via SMS',
      type: CHECKIN_TYPES.SMS,
    })

    let dmsReset = false
    if (dmsId) {
      await dmsRepo.reset(dmsId, activeDms.interval_minutes, activeDms.interval_seconds)
      dmsReset = true
    }

    return { checkin, dmsReset }
  })

  await inboundRepo.markParsed(record.id, tourist.id, null)
  emitCheckinUpdate(tourist.id, tourist.guardian_token, null, null, null)

  logger.info({ touristId: tourist.id, dmsReset, from: fromPhone }, 'SMS check-in processed')
  return { checkin, dmsReset }
}

module.exports = { processInboundSMS, classifyInboundSMS }
